name: ADLC3
on: 
  push:
    branches:
      - 'v[0-9]{1,2}.[0-9]{1,2}'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Commit Message
        run: |
          if [[ "${{ github.event.head_commit.message }}" == '#NORUN'* ]]; then
            echo "Commit message starts with #NORUN. Skipping the pipeline."
            exit 0
          fi
      - name: Checkout Code
        uses: actions/checkout@v2

        
