name: 
on: 
  push:
    branches:
      - 'v[0-9]+\.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Check Commit Message
      #   run: |
      #     if [[ "${{ github.event.head_commit.message }}" == '#NORUN'* ]]; then
      #       echo "Commit message starts with #NORUN. Skipping the pipeline."
      #       exit 0
      #     fi
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: 'trivy-results.sarif'
  dockerBuildPush:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest





